baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'poison'
pluralizelisttitles = false

[params]
    brand = "Test"
    menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Publications", URL = "/publications/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
    ]
